### ISSUE TITLE
Getting invalid XML output

### ISSUE THREAD

**Issue by pdiveris** [spatie/laravel-feed#101]
I am getting a strange error to the effect that the document is invalid

#### This page contains the following errors:
`error on line 1 at column 10: XML declaration allowed only at the start of the document`

If I view the source of the feed generated, it appears to contain a few blank characters in the beginning (before the xml tag)

![Screenshot 2019-08-02 at 02 09 49](https://user-images.githubusercontent.com/1022373/62337039-e16e3380-b4ca-11e9-9953-6330c448f2f9.png)

If I completely remove the XML version/encoding declaration then Chrome plays the feed OK:

![Screenshot 2019-08-02 at 02 14 10](https://user-images.githubusercontent.com/1022373/62337124-3f9b1680-b4cb-11e9-9cc4-6525f23274ff.png)

I am not sure as to where the spaces are being added.

**Comment by rubenvanassche** [comment]
Hi @pdiveris can you share some more information about your configuration? Did you overwrite the view that's rendering the feed?

**Comment by pdiveris** [comment]
My configuration to start with was vanilla, running with Laravel 5.8.28 and having installed as per instructions `composer require spatie/laravel-feed`, I added the `Route::feeds('/feed');` to my `web.php` and the 

``
use Spatie\Feed\Feedable;
use Spatie\Feed\FeedItem;

..
class ProposalView extends Model implements Feedable
```

to my model. I then simply visited `https://www.sixacts.org/feed/feed` link (after adding the `@include('feed::links')` to my layout. If you view the link right now it will appear OK, as I've removed the `<?xml ` bit from it. But if I use the official view (attached here) then I get the error I reported. I don't know if that matters but shoer tags are off in my php.ini. I can resurrect the problem on a beta URL if that helps.

**Comment by rubenvanassche** [comment]
Can you try replacing 
```php
<?=
    /* Using an echo tag here so the `<? ... ?>` won't get parsed as short tags */
    '<?xml version="1.0" encoding="UTF-8"?>'.PHP_EOL
?>
```

with:
```php
{!! '<?xml version="1.0" encoding="UTF-8"?>' !!}
```

in `vendor/spatie/laravel-feed/resources/views>/feed.blade.php` ?

**Comment by pdiveris** [comment]
Yes sure, I just did. In fact I think I tried the something similar last night as well. I am getting the same issue ;o(

I cannot insist that it's neccessarily not a problem with my setup, i.e. some middleware writing out but I very much doubt it as I don't have any custom middleware attempting to write to anything.

**Comment by pdiveris** [comment]
Hi. I just did, I am getting the same I am afraid ;o(

**Comment by pdiveris** [comment]
If it's any help, anything I put in the file, say <bob></bob> seems to start after a few spaces, five to be precise.

![Screenshot 2019-08-02 at 01 19 07](https://user-images.githubusercontent.com/1022373/62356450-04b7d380-b509-11e9-96ac-6cf6ae0f0051.png)

**Comment by rubenvanassche** [comment]
Hi @pdiveris I've replicated your steps with a clean Laravel installation and do not have any problems with generating a valid XML feed. Maybe check those middlewares you mentioned earlier? When I check your example feed, the `<feed>` tag is also indented, which isn't in my clean Laravel installation. This could be a starting point to solve your issue?

I will close the issue for now, feel free to reopen it if you can find a problem with the package.

**Comment by pdiveris** [comment]
I will keep investigating. The problem persists even if disable 3rd party middlewares, although I don't have the time to do a fresh install etc etc. I appreciate you want to close the ticket, that's fine, but can you spare a minute and guide me to the point (in your code) where I can grab the generated stream (text) before it gets spat out to the "view." Is there a point inthe code where such string exists so I could examin (write it to a file for instance.)

**Comment by rubenvanassche** [comment]
You can check the `toResponse` method in `Feed.php`

**Comment by pdiveris** [comment]
Thank you. I interecepted that and wrote out on a file what `$contents` contains at that moment. See file attached, no spaces. It's the weirdest problem I've come across in the past few months..

[feed.txt](https://github.com/spatie/laravel-feed/files/3460886/feed.txt)
