### ISSUE TITLE
Make package more dynamic

### ISSUE THREAD

**Issue by SamuelNitsche** [spatie/laravel-feed#102]
Hey guys, I currently use this package to create an iTunes RSS Feed. Most things work fine when using a custom view but I noticed that some fields are required for the `FeedItem` which I don't use in the blade view.

Maybe we can move the required fields to the config file instead of hardcoding it. What do you think?

**Comment by freekmurze** [comment]
Sure, whip up a PR. If it is simple enough, I'll consider merging it in. 👍
