### ISSUE TITLE
mix of RSS and Atom

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-feed#108]
Atm the package mixes RSS and Atom. The blade feed view renders an Atom feed but the blade link view generates RSS link tags.
https://github.com/spatie/laravel-feed/blob/732d840cfa6c0369a48fb32d136b812dc3d97ab1/resources/views/links.blade.php#L2
`type="application/atom+xml"` would be correct.

My idea would be to add a new key to the config array which contains the html link type. And if it's `!$type === true` it doesn't render this feed in the links.
This would allow to do everything the right way. I also suggest to add a RSS feed view to generate rss feeds.

**Comment by freekmurze** [comment]
Send a PR to correct the type, and then separate PRs for the other things you are proposing. 👍
