### ISSUE TITLE
Add content attribute to FeedItem

### ISSUE THREAD

**Issue by tonoslav** [spatie/laravel-feed#111]
Hey there Im trying to use this awesome generator to create feed for Google News and they require to set full article in feed, **content** attribute is needed

https://validator.w3.org/feed/docs/atom.html#contentElement
https://support.google.com/news/producer/answer/6170026?hl=en (see Sample Atom 1.0 feed)

I recommend to add just copy of **summary** but just as **optional**

I am not good at PRs so I only can recommend it like this, sorry but it doesn't looks like it should be difficult

**Comment by freekmurze** [comment]
I currently don't have a need myself for extra fields, so I'm not going to invest time in adding them.
