### ISSUE TITLE
The feed does not seem to validate

### ISSUE THREAD

**Issue by FreddyCrugger** [spatie/laravel-feed#114]
This feed does not validate.

line 6, column 32: Undefined feed element: description [help]

                                <description>Our  News is for Coders a ...
                                ^
line 7, column 32: Undefined feed element: language [help]

                                <language>en-US</language>
                                ^
line 8, column 72: updated must be an RFC-3339 date-time: Thu, 07 Nov 2019 18:37:47 +0100 [help]

                                <updated>Thu, 07 Nov 2019 18:37:47 +0100</up ...
                                                                        ^
line 19, column 24: Missing category attribute: term (26 occurrences) [help]

                        <category type="html">
                        ^
line 19, column 24: Unexpected type attribute on category element (26 occurrences) [help]

                        <category type="html">
                        ^
line 22, column 52: updated must be an RFC-3339 date-time: Wed, 05 Jun 2019 16:19:15 +0200 (26 occurrences) [help]

            <updated>Wed, 05 Jun 2019 16:19:15 +0200</updated>
                                                    ^
In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendations.

line 2, column 0: Missing atom:link with rel="self" [help]
Tested here:

<feed xmlns="http://www.w3.org/2005/Atom">
line 32, column 0: Invalid HTML: EOF in middle of construct, at line 2, column 211 (3 occurrences) [help]

                <![CDATA[<h1>How To Protect Vue Routes With Roles</h1><p><br ...
line 62, column 0: summary should not contain spellcheck attribute (3 occurrences) [help]

                <![CDATA[<p>How to remove a specific item from a list in Vue ...

**Comment by freekmurze** [comment]
Feel free to PR improvements around this.

**Comment by channaveer** [comment]
@FreddyCrugger @freekmurze Even I am facing the same problem any updates on the resolution.

**Comment by freekmurze** [comment]
I don’t have time to handle this atm. Feel free to PR a fix 👍

**Comment by channaveer** [comment]
@freekmurze Can you please help me with what should I look for. So that I can at least go ahead and dive into it

**Comment by vwasteels** [comment]
@channaveer did you succeed to make to work ?
thanks

**Comment by channaveer** [comment]
@vwasteels I wrote my own code to solve it.

**Comment by vwasteels** [comment]
Ok I guess I'll have to do this too

**Comment by FreddyCrugger** [comment]
I ended up using this format in my Laravel app in a past project.
https://kollox.com/php-rss-feed/

Hope this helps.
