### ISSUE TITLE
Undefined variable: namespaces 

### ISSUE THREAD

**Issue by KalimeroMK** [spatie/laravel-feed#115]
<img width="1438" alt="Screen Shot 2019-12-14 at 11 48 03" src="https://user-images.githubusercontent.com/24772657/70847697-a3652100-1e67-11ea-84c7-11ba5d0180bc.png">

**Comment by freekmurze** [comment]
Could you try upgrading to the latest version of the package?

**Comment by KalimeroMK** [comment]
I already use the last version, the project is built on laravel 6.7

**Comment by freekmurze** [comment]
The view in your exception trace isn't present in the latest version of the package.

**Comment by KalimeroMK** [comment]
can you tell me which file it is to copy from git and add manual

**Comment by freekmurze** [comment]
Do not copy files manually, but use composer

https://github.com/spatie/laravel-feed#installation

Make sure composer installs v2 (use `composer show` to verify that)
