### ISSUE TITLE
Special characters being displayed in feed title

### ISSUE THREAD

**Issue by choxx** [spatie/laravel-feed#116]
Hi there!
Here is the schema of my table:
```
CREATE TABLE `posts` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```
If I store the title like as shown in the screenshots, they are being encoded while listing feed.
![Mysql](https://user-images.githubusercontent.com/11666456/71474902-b8e13000-2803-11ea-88a0-3b24915f5183.png)
![feed](https://user-images.githubusercontent.com/11666456/71474979-3442e180-2804-11ea-9154-9b2a2d5b7026.png)

How to fix it?

**Comment by SurfJunky** [comment]
you can get ride of this characters
example
`'title' => strip_tags($this->title),`

**Comment by choxx** [comment]
Hi @SurfJunky, Thanks for the reply. 
Definitely I'd like to keep this(special) character(s). So, the second solution you have suggested is not at all the obvious choice.
Regarding the first solution, are you saying I should edit the source code in the package directly?
Won't this break the future updates for this package to me? Also, this wouldn't be git tracked so I have to separately maintain code versions on my local & server.

**Comment by SurfJunky** [comment]
> Regarding the first solution, are you saying I should edit the source code in the package directly?
> Won't this break the future updates for this package to me? Also, this wouldn't be git tracked so I have to separately maintain code versions on my local & server.

Ofc not your going to edit a view file you can customize the style aswell.
but you still can publish the views and fix the problem without touching the original files.
Thanks

**Comment by choxx** [comment]
Thanks @SurfJunky
It's fixed with the change you have suggested.
