### ISSUE TITLE
5.3: [InvalidArgumentException] Route [spatieLaravelFeed0] not defined

### ISSUE THREAD

**Issue by benjamincrozat** [spatie/laravel-feed#12]
Hello,

So yesterday I branched my website and migrated to Laravel 5.3. Packages seem up to date but I have this error message from spatie/laravel-feed and I didn't even changed any spatie/laravel-feed related code:
```
[InvalidArgumentException]               
Route [spatieLaravelFeed0] not defined.  
```

**Comment by freekmurze** [comment]
Seems to be working in my tests. Have you setup the routes?

```php
// in your routes file
Route::feeds();
```

**Comment by benjamincrozat** [comment]
I'm so sorry, the service provider wasn't at the right place. I don't know why. I was probably drunk, ha ha.
