### ISSUE TITLE
 Invalid argument supplied for foreach() 

### ISSUE THREAD

**Issue by ridwanmubarok** [spatie/laravel-feed#122]
how to solve problem ?

**Comment by freekmurze** [comment]
There's too little information here to help you. Consider give us as much info as possible when opening up an issue.

**Comment by dcemal** [comment]
Basically I get the same problem,

When I install package and add Route::feeds(); to my web.php, and when I refresh the page it gives error as;

ErrorException
Invalid argument supplied for foreach()

The highlighted area is: vendor/spatie/laravel-feed/src/FeedServiceProvider.php:39

And when i try to publish config file via following code, it gives me the same error in console:
php artisan vendor:publish --provider="Spatie\Feed\FeedServiceProvider" --tag="config"
