### ISSUE TITLE
Too few arguments to function Spatie\Feed\Feed::__construct(), 4 passed in C:\xampp\htdocs\facts\packages\spatie\laravel-feed\src\Http\FeedController.php on line 30 and exactly 6 expected

### ISSUE THREAD

**Issue by abidshah544** [spatie/laravel-feed#125]

**Comment by freekmurze** [comment]
The test of the package prove that it is working correctly. This error must be caused to something specific in your app. Please try installing the package in a vanilla Laravel app.
