### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by dcemal** [spatie/laravel-feed#127]
When I install package and add Route::feeds(); to my web.php, and when I refresh the page it gives error as;

ErrorException
Invalid argument supplied for foreach()

The highlighted area is: vendor/spatie/laravel-feed/src/FeedServiceProvider.php:39

And when i try to publish config file via following code, it gives me the same error in console:
php artisan vendor:publish --provider="Spatie\Feed\FeedServiceProvider" --tag="config"

**Comment by senbai** [comment]
# Reason:
laravel Can't See The `feed` file after install the package.

# Solution:

Just Clear you cache  by simply type in the` terminal` or the `command prompt` 
```
php artisan cache:clear
```

**Comment by bsh** [comment]
Or you can delete the contnet of the /bootstrap/cache foldler.
