### ISSUE TITLE
Typed property Spatie\Feed\FeedItem::$author must not be accessed before initialization

### ISSUE THREAD

**Issue by DominikGeimer** [spatie/laravel-feed#160]
Hi,

I followed the instruction, but I get the following error when I access /feed.

`Typed property Spatie\Feed\FeedItem::$author must not be accessed before initialization`

This is my toFeedItem() function:

```
public function toFeedItem(): FeedItem
    {
        return FeedItem::create([
            'id' => $this->slug,
            'title' => $this->title,
            'summary' => $this->excerpt,
            'updated' => $this->updated_at,
            'link' => env('APP_URL').'/'.$this->slug,
            'authorName' => 'Dominik Geimer',
        ]);
    }
```

Any Idea whats wrong?

**Comment by freekmurze** [comment]
Could you post the full stack trace? Or share the error via Flare?

**Comment by DominikGeimer** [comment]
Hello,

here is the Flare link for this error. And btw thanks for your great packages and of course Flare :-)
https://flareapp.io/share/xmN6aXxm

**Comment by freekmurze** [comment]
Which version of the package are you using? If possible, upgrade to the latest version.

You can check the used version with `composer show`

**Comment by DominikGeimer** [comment]
Thanks for the hint! I don't know why but composer pulled in an old version. I fixed that and the error is gone!

Thank you!
