### ISSUE TITLE
Installation bug

### ISSUE THREAD

**Issue by Naxon** [spatie/laravel-feed#18]
Hi,

I get the following errors when running `composer require spatie/laravel-feed`:

```

  [InvalidArgumentException]
  Route [spatieLaravelFeed0] not defined.


Script php artisan optimize handling the post-update-cmd event returned with an error

Installation failed, reverting ./composer.json to its original content.


  [RuntimeException]
  Error Output:

```

**Comment by freekmurze** [comment]
I could not reproduce your problem 
![screen shot 2016-10-17 at 10 44 24](https://cloud.githubusercontent.com/assets/483853/19430967/b425810e-9456-11e6-8824-f8403afc9f60.png)

You can workaround this issue by temporarly the content in the `post-update-cmd` key in your `composer.json`, running `composer require spatie/laravel-feed` and adding back the commands.
