### ISSUE TITLE
Routes have to be defined to publish

### ISSUE THREAD

**Issue by redgluten** [spatie/laravel-feed#2]
The readme file states that you should publish your config before registering your routes doing it this way throws the following error:  `[InvalidArgumentException] Route [spatieLaravelFeed0] not defined`.

I thought about submitting a pull request to change the readme but this seems like a bug as it would prevent installation of others packages?

**Comment by JolitaGrazyte** [comment]
Thank you for letting it know. 
You must indeed first register the Route::feed() in your route.php and only then publish the config file. 
Like that it works fine.

I have updated the README file.

**Comment by nWidart** [comment]
I added the `Route::feeds();` and yet I'm getting ` Route [spatieLaravelFeed0] not defined.`.
