### ISSUE TITLE
Custom Views

### ISSUE THREAD

**Issue by MisterMarlu** [spatie/laravel-feed#33]
Hey, is there any way to use custom templates instead of the default?

In my project I extended your Feed.php to get my custom template:

    public function getFeedContent()
    {
        list($class, $method) = explode('@', $this->feedConfiguration['items']);

        $items = app($class)->{$method}();

        $meta = ['id' => url($this->feedConfiguration['url']), 'link' => url($this->feedConfiguration['url']), 'title' => $this->feedConfiguration['title'], 'updated' => $this->getLastUpdatedDate($items)];

        $view = $this->feedConfiguration['view'] ?? 'laravel-feed::feed';

        return view($view, compact('meta', 'items'))->render();
    }

**Comment by freekmurze** [comment]
I've just tagged a new release that enables you to publish the views.
