### ISSUE TITLE
Passing a parameter to the `getFeedItems()` method

### ISSUE THREAD

**Issue by leedriscoll** [spatie/laravel-feed#37]
Using the example from the documentation, I have a `NewsItem model` and I want to generate multiple rss feeds for different NewsItems filtered by category. I have 10+ categories and I'd like to generate an rss feed for each of them.

Is there a way of passing a parameter to the `getFeedItems()` method on my `NewsItem model` so I don't have to create multiple methods on my model as follows

```php
// I'd like to do something like this
public function getFeedItems($category)
{
    if (! is_null($category)) {
       return NewsItem::where('category', $category)->get(); 
    }
   return NewsItem::all();
}

// instead of something like this
public function getFeedItemsForCategoryOne()
{
   return NewsItem::where('category', 1)->get();
}

public function getFeedItemsForCategoryTwo()
{
   return NewsItem::where('category', 2)->get();
}
```

Could we add a new parameter to the content of the published file laravel-feed.php:

```php
return [

    'feeds' => [
        [
            /*
             * Here you can specify which class and method will return
             * the items that should appear in the feed. For example:
             * '\App\Model@getAllFeedItems'
             */
            'items' => '\App\NewsItem@getAllFeedItems',

            /*
             * The feed will be available on this url.
             */
            'url' => '/news/feed',

            /* add a new parameter */
            'some_parameter' => 1

            'title' => 'My Title',
        ],
    ],
];
```

And then pass the new paramerter to the model class through the `getFeedContent()`method in `feed.php`

```php
public function getFeedContent()
{
    list($class, $method) = explode('@', $this->feedConfiguration['items']);

    $items = app($class)->{$method}($this->feedConfiguration['some_parameter']);
    ...
```

Let me know your thoughts, I'm happy to do the work and submit a PR if you can give me some guidance on how you'd like this implemented.

**Comment by sebastiandedeyne** [comment]
Something like this would make sense to me:

```php
return [
    'feeds' => [
        [
            'items' => ['App\NewsItem@getFeedItemsForCategory', 'news'],
            // ...
        ],
    ],
];
```

What do you think @freekmurze?

**Comment by freekmurze** [comment]
@sebastiandedeyne's suggestion seems like the way to go 👍 

I'd accept a fully tested, non-breaking PR that adds this to the package.

**Comment by leedriscoll** [comment]
Cool - I'll get on it 😄

**Comment by leedriscoll** [comment]
How does this implementation look for a first go? @sebastiandedeyne @freekmurze 

https://github.com/spatie/laravel-feed/compare/master...leedriscoll:pass_parameter_to_getFeedItems()?expand=1

__Tests not written yet__ - Can you give me some guidance on this, please?

**Comment by seanhudson** [comment]
Nice. I just started working on this today and need the same functionality.

**Comment by leedriscoll** [comment]
Hey guys, 

The tests have been refactored. 
Can you give me feedback on the proposed changes before I create a PR?

https://github.com/spatie/laravel-feed/compare/master...leedriscoll:pass_parameter_to_getFeedItems()?expand=1

Thanks 😃

**Comment by freekmurze** [comment]
Hi,

just go ahead and create a PR, that 'll make it easier for us to comment on things. We'll handle this further on that new PR.

Thanks for all your efforts!
