### ISSUE TITLE
Where do views get published?

### ISSUE THREAD

**Issue by seanhudson** [spatie/laravel-feed#39]
php artisan vendor:publish --provider="Spatie\Feed\FeedServiceProvider" --tag="views"

Doesn't seem to do anything

**Comment by sebastiandedeyne** [comment]
Looks like the `views` tag was missing from our service provider, so that command wasn't doing anything. Just tagged `1.3.1`, if you run `composer update` they should be published in `resources/views/vendor/laravel-feed`!
