### ISSUE TITLE
Invalid RSS feed

### ISSUE THREAD

**Issue by nWidart** [spatie/laravel-feed#4]
Hello,

I've tested an rss feed generated from this package, however the w3 validator says some items are invalid.

Here is the result of the test: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fnicolaswidart.com%2Frss

Did I miss something to avoid this ? 

Thanks,

**Comment by freekmurze** [comment]
I'll take a look at this in the coming weeks. If you need a quick fix, I'd accept a PR that fixes this.

**Comment by nWidart** [comment]
Alrighty thanks. Enjoy the sun! ☀️ 

It's not very urgent, I'll see if I can fin time.

**Comment by sebastiandedeyne** [comment]
I tagged a new version that got rid of an unnecessary `CDATA` wrapper, it might fix those validation issues, let me know of something's still off!

**Comment by nWidart** [comment]
Thanks I'll test it out later today.

**Comment by nWidart** [comment]
Awesome, the feed is [now valid](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fnicolaswidart.com%2Frss). 

Thanks again! 👍
