### ISSUE TITLE
W3C RSS Validator Failed

### ISSUE THREAD

**Issue by GiampaoloFalqui** [spatie/laravel-feed#46]
https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fapi.cambiomarcia.com%2Frss%2Ffeedbacks

You can see here that W3C validator fails to validate the RSS.

We are trying to use it on a WordPress widget however it fails to load the data.

The version I am using is a fork of laravel-feed I have made, just to add lumen and custom attributes support.

It is probably because of something I have done (I have noticed that the 'image' attributes is not recognized), however looking at many other RSS feeds, it seems like yours is missing the channel node?

Oh, and out of curiosity, what specification is laravel-feed based on? RSS 2.0?

**Comment by GiampaoloFalqui** [comment]
Removing the image tag, the validation had success, however we are still struggling to make it work.

Could it be because the channel node is missing?

**Comment by sebastiandedeyne** [comment]
This package generates an Atom feed, I don't see any mentions of `channel` in the spec at first sight.

https://validator.w3.org/feed/docs/atom.html
