### ISSUE TITLE
Feed Pagination

### ISSUE THREAD

**Issue by acitjazz** [spatie/laravel-feed#47]
Can we create feed with pagination?

	`public function getFeedItems() {
		return Post::paginate(30);
	}`

**Comment by freekmurze** [comment]
Why would you want to paginate the feed?
What is the expected result?

**Comment by acitjazz** [comment]
i have more than 10000 article,, and when user visit link my feed ,, the feed query all my data and make it crash,,  so what i have to do?


i'm sorry about my english..

**Comment by freekmurze** [comment]
How about just limiting the result? Here's an example on how to get only 100 posts.

```
public function getFeedItems() {
	return Post::take(100)->get();
}
```

Of course you should add some sorting logic so you get the latest 100 (or whatever amount you prefer) posts.
