### ISSUE TITLE
phpunit-snapshot-assertions required?

### ISSUE THREAD

**Issue by Stefan-ST** [spatie/laravel-feed#51]
`spatie/phpunit-snapshot-assertions` is both listed in `require` and ` require-dev` in composer file which seems odd. Is is really required for using (not testing) this package? It adds PHPUnit and all its dependencies even in production environment.

**Comment by sebastiandedeyne** [comment]
Looks like that accidentally slipped in there! Tagged a new version without the unnecessary dependency.
