### ISSUE TITLE
getting authors name

### ISSUE THREAD

**Issue by robertnicjoo** [spatie/laravel-feed#69]
Hi,

How can I provide author name in my feed because i get user_id and not their name in my posts table.
In blade i use like `{{$post->user->name}}` in `->author($this->author);` what should i use?

Thanks.

**Comment by freekmurze** [comment]
This question is project specific. Our code doesn't care how the author name is fetched.

**Comment by robertnicjoo** [comment]
you made author name required then you say we not care! well done.
