### ISSUE TITLE
Allow custom sort order configuration for feed items

### ISSUE THREAD

**Issue by robertnicjoo** [spatie/laravel-feed#71]
hi,

how can I implement `->orderby('id', 'desc')` to my feeds?
currently feed are like

```html
id 1
id 2
....
new feed
```

it supposed to be 

```html
new feed
....
id 2
id 1
```

**Comment by sebastiandedeyne** [comment]
Feeds are date-sensitive, why would you want to use a different order?

**Comment by robertnicjoo** [comment]
So please tell me how to use dates? As i mentioned in my question my feeds seems to be id sensitive! Mid 1 is always is in the top.

**Comment by sebastiandedeyne** [comment]
Could you share as much code as possible so I can see what you're doing now? Also, what package version are you using?

**Comment by robertnicjoo** [comment]
Sorry I'm with phone can't have access to my codes so i uploaded images of my codes you asked for.


1. https://ibb.co/kGz12o
2. https://ibb.co/eJUUoT

**Comment by sebastiandedeyne** [comment]
Feeds are sorted by `updated_at`. If al your `updated_at` values are the same (which is a common case with dummy data), they're probably in the same order as the database which is by `id`.

Is this your issue?

**Comment by robertnicjoo** [comment]
My posts `updated_at` are not same as `created_at` not all of them at least, i have postes with revisions as well. Now whats do you suggest me?

**Comment by sebastiandedeyne** [comment]
I'd accept a non-breaking PR that adds a `pubdate` field to the feed based on a `published_at` attribute.

**Comment by robertnicjoo** [comment]
Meaning?
Should i change something or what?

**Comment by robertnicjoo** [comment]
Why don't you just use id instead of adding new field to tables?!

**Comment by sebastiandedeyne** [comment]
Sorry, missed part of the issue and misunderstood.

Our package currently only supports sorting by `updated_at`, it's hard coded. I wouldn't mind having a `sort_by` configuration item in the configuration (https://github.com/spatie/laravel-feed/blob/master/config/feed.php) so you can sort the feed in whatever order you prefer.

I don't have time to implement this myself the next few weeks, so if it's urgent, feel free to send a tested PR that adds a `sort_by` option to the feed configuration, and I'll gladly review and release it 👍

**Comment by robertnicjoo** [comment]
I published pr but I'll look into your suggestion as well

https://github.com/spatie/laravel-feed/pull/72

Thanks for your time.

**Comment by atymic** [comment]
PR open in #94 :smile:

**Comment by freekmurze** [comment]
Continuing the conversation in #94
