### ISSUE TITLE
Route caching

### ISSUE THREAD

**Issue by Cannonb4ll** [spatie/laravel-feed#8]
When using `Route::feeds();` it is not possible to cache your routes. (`php artisan route:cache`)

Returning error:

```
  [LogicException]
  Unable to prepare route [feed] for serialization. Uses Closure.
```

Is it possible to fix this?

**Comment by sebastiandedeyne** [comment]
We might look into replacing the closure with a controller action in future versions, but that probably won't happen any time soon.

I see the value of converting it though, so a PR's welcome if you'd need it sooner!
