### ISSUE TITLE
Support for Signed URLs

### ISSUE THREAD

**Issue by nerg4l** [spatie/laravel-feed#80]
Since Laravel 5.6 the UrlGenerater can generate [Signed URLs](https://laravel.com/docs/5.6/urls#signed-urls).

It would be greate if we could use this to create personal/private feeds for clients.

**Comment by freekmurze** [comment]
If the code is simple, well tested and documented, I'd consider pulling in a PR for this.

**Comment by nerg4l** [comment]
I'm not promising anything but I'll give it a try.
