### ISSUE TITLE
Undefined offset: 0

### ISSUE THREAD

**Issue by Houssem-Guemer** [spatie/laravel-feed#82]
hi , i really like you work and i was trying to use it in my project , but i had this error after adding Route::feeds into my web.php and i need your help , thanks .

in Router.php (line 1215)

**Comment by freekmurze** [comment]
Try clearing the config cache with `php artisan config:cache`

**Comment by TimmKroe** [comment]
Still having that issue even after config clear and config cache

**Comment by smartbos** [comment]
Hi

Thanks for the good package.

I've got this issue too.

When I try to get feeds by web browser, it works well.
But I can't run phpunit. When I try it resulted below.

```
In Router.php line 1275:
                       
  Undefined offset: 0  
```

I tried `php artisan config:cache` but it didn't work.
Can you review this issue again?

Thanks
