### ISSUE TITLE
Installation bug

### ISSUE THREAD

**Issue by amjad-eremnews** [spatie/laravel-feed#89]
our requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for spatie/laravel-feed ^2.2 -> satisfiable by spatie/laravel-feed[2.2.0].
    - Conclusion: remove nesbot/carbon 2.14.2
    - Conclusion: don't install nesbot/carbon 2.14.2
    - spatie/laravel-feed 2.2.0 requires nesbot/carbon ^1.0 -> satisfiable by nesbot/carbon[1.0.0, 1.0.1, 1.1.0, 1.10.0, 1.11.0, 1.12.0, 1.13.0, 1.14.0, 1.15.0, 1.16.0, 1.17.0, 1.18.0, 1.19.0, 1.2.0, 1.20.0, 1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.3.0, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0].

**Comment by freekmurze** [comment]
I've just release a version that is allows carbon v2
