### ISSUE TITLE
Template issue

### ISSUE THREAD

**Issue by robertnicjoo** [spatie/laravel-feed#90]
This is how my feed returning and i don't know why
![12](https://user-images.githubusercontent.com/8672823/56074817-fc654c80-5de2-11e9-92d2-cec54e76d94c.png)

this is my `feed.php`
```php
<?php

return [
    'feeds' => [
      'main' => [
            'items' => 'App\Post@getFeedItems',
            'url' => '/articles-feed',
            'title' => config('app.name') . ' - Articles feed',
            'view' => 'feed::feed',
        ],
    ],
];
```

here is my model

```php
public function toFeedItem()
    {
        return FeedItem::create()
            ->id($this->id)
            ->title($this->title)
            ->summary('new article is published')
            ->updated($this->updated_at)
            ->link('blog/'.$this->slug)
            ->author($this->user->name);
    }

    public static function getFeedItems()
    {
       return Post::all();
    }
```

any idea?

**Comment by sebastiandedeyne** [comment]
Could it be that your webserver is doing something wrong with the headers?

If you change the feed to `/articles-feed.xml`, does it work?

**Comment by robertnicjoo** [comment]
that didn't help.

Maybe it worth to mention in mobile browser it shows feeds with xml template, the issue above just happens in PC browsers.

**Comment by atymic** [comment]
Can you post the raw HTML is a gist please?

**Comment by atymic** [comment]
@robertnicjoo 
Did you get this resolved?

**Comment by robertnicjoo** [comment]
No it shows the same as i mentioned but functionality hasnt change since old versions.

So it works, but show codes badly.

**Comment by sebastiandedeyne** [comment]
Please share the full feed output if this is still an issue.
