### ISSUE TITLE
Update XML schema for Flipboard support

### ISSUE THREAD

**Issue by nikhiltri** [spatie/laravel-feed#91]
Hey all,

I'm currently working on my own fork of this project to update the XML schema to provide support of Flipboard's RSS guidelines:

https://about.flipboard.com/rss-spec/

Are these changes you'd be interested in adopting into the main codebase? If so, I'll submit a PR when I'm done.

Thanks!
nikhil

**Comment by sebastiandedeyne** [comment]
Could you share a quick overview of what the changes would include? What does Flipboard expect that isn't covered by the base spec?

**Comment by nikhiltri** [comment]
Most of what's needed include renaming a few of the fields, which I can do in a custom view. What I'm adding to my fork of this project is a few additional fields:

* Feed.description
* Feed.language
* FeedItem.enclosure (for a representative image or video)

**Comment by nikhiltri** [comment]
See my WIP here: https://github.com/nikhiltri/laravel-feed/commits/feature/support-for-flipboard

Likely just one more commit for the enclosure field before it's ready for a PR.

**Comment by pdiveris** [comment]
Erm.. I am getting a weird issue with "spatie/laravel-feed": "^2.2" where Chrome is reporting to me that 
#### This page contains the following errors:
```
error on line 1 at column 10: XML declaration allowed only at the start of the document
```

If I look at the generated output this is what I see

![Screenshot 2019-08-02 at 01 19 07](https://user-images.githubusercontent.com/1022373/62335395-943a9380-b4c3-11e9-9346-4ad933029b2c.png)

It seems to be adding some spaces before the XML tag. 

If I totally remove the XML declaration from the view then it works, albeit without the declaration..

**Comment by freekmurze** [comment]
Feel free to send a PR that adds these things in a non-breaking way. Be sure to include updated tests 👍
